In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to tensors
### Creating tensors:
torch.tensor is the common class to create and manipulate tensors in pytorch.

In [ ]:
# Creating a scalar:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# the dimension of a scalar tensor:
scalar.ndim

0

In [ ]:
# To get a regular python integer from this tensor:
scalar.item()

7

In [ ]:
# Vector:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# How many dimensions of a vector:
vector.ndim

1

In [ ]:
# Shape of a vector:
vector.shape

torch.Size([2])

In [ ]:
# Matrix:
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# How many dimensions of a matrix:
MATRIX.ndim

2

In [ ]:
# Shape of a matrix:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Accessing to a row:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# Tensor:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# Dimension of a tensor:
TENSOR.ndim

3

In [ ]:
# Shape of a tensor:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random tensors:
### Why random tensors:
Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers .

In [ ]:
# create a random tensors of size (3,4):
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0651, 0.3591, 0.5631, 0.4132],
        [0.3872, 0.4422, 0.9412, 0.0133],
        [0.3584, 0.9780, 0.4422, 0.7848]])

In [ ]:
# create a random tensor with similar shape to an image tensor:
random_image_size_tensor = torch.rand(size=(224, 224, 3))

## Zeros and ones

In [ ]:
# create a tensor of all zeros:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range of tensors and tensors-like

In [ ]:
# use torch.arange:
one_to_five = torch.arange(1,6)
one_to_five

tensor([1, 2, 3, 4, 5])

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors datatypes
**Note:** Tensor datatypes is one of the 3 bog errors you will into with pytorch:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device='cpu', # What device is your tensor on
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# sknow the dtype of elments in the tensor:
float_32_tensor.dtype

torch.float32

In [ ]:
# convert the stype of a tensor:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

## Getting informations from tensors

1. To get datatype from a tensor can use **tensor.dtype**.
2. To get shape from a tensor can use **tensor.shape**.
3. To het device from a tensor can use **tensor.device**.

In [ ]:
# create a tensor:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5390, 0.4644, 0.9886, 0.7467],
        [0.8220, 0.9020, 0.3368, 0.1116],
        [0.8382, 0.8415, 0.0719, 0.3408]])

In [ ]:
# print the datatype:
print(some_tensor.dtype)
# print the shape:
print(some_tensor.shape)
# print the device:
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


## Tensor operations

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [ ]:
# Add to all the elements in tensor;
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply all the elemnts in the tensor by a scalar:
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract from all the elements a scalar:
tensor - 10

tensor([-9, -8, -7])

### Matrix multiplication
Matrix multiplication include:

1. Element wise multiplication
2. Matrix multiplication

In [ ]:
# Element wise multiplication:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix miltiplication:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# We can_t perform matmul because the shapes are : (3,2) @ (3,2)


To fix our tensors shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

In [ ]:
# Apply the transpose for a tensor:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# torch.mm is the same as torch.matmul, now we can apply matmul by using transpose:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum: (tensor aggregation)


In [ ]:
# Create a tensor:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min with 2 methods:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean, we should convert the tensor dtype to float:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# Finding the position of the min:
x.argmin()

tensor(0)

In [ ]:
# Find the position of the max:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping : Reshapes an input tensor to a defined shape.
* View : Return a view of an input tensor of certain shape but keep the same as the original tensor.
* Stacking : Combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze : Removes all 1 dimension from a tensor.
* Unsqueeze : Add a 1 dimension to a target tensor.
* Permute : Return a view of the input with dimensions permuted(swapped) in a certain way.


In [ ]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Reshape the tensor with a valid shape
# --> meaning we connot reshape a tensor of 9 element with shape (1,7)
# reshape from a vector to a matrix row
x_reshaped = x.reshape(1,10)
x.shape, x_reshaped.shape

(torch.Size([10]), torch.Size([1, 10]))

In [ ]:
# reshape from a vector to a matrix col
x_reshaped = x.reshape(10,1)
x.shape, x_reshaped.shape

(torch.Size([10]), torch.Size([10, 1]))

In [ ]:
# reshape from a vector to matrix of 10 elements to attend a valid shape:
x_reshaped = x.reshape(5,2)
x.shape, x_reshaped.shape

(torch.Size([10]), torch.Size([5, 2]))

Change the view : Changing z changes x because a view shares the same memory as the original input.

In [ ]:
# Change the view:
z = x.view(1,10)
z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
# Change z :
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other: stacked vertically
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
# Stack tensors on top of each other: stacked horizontally
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
x_stacked.shape

torch.Size([10, 4])

In [ ]:
# torch.squeeze: remove all single dimensions from a target tensor
x_reshaped = x.reshape(1, 10)
x_reshaped

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
# squeeze the x_reshaped from a matrix of shape (1, 10) to a vector of 10 elements
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# unsqueez a tensor : adds a single dimension to a target:
x_unsqueezd = x_squeezed.unsqueeze(dim=0)
x_unsqueezd

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_unsqueezd = x_squeezed.unsqueeze(dim=1)
x_unsqueezd

tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [ ]:
# permute: rearranges the dimensions of a target tensor in a specific order:
x_original = torch.rand(size=(2,2,3))
# permute the original tensor:
x_permuted = x_original.permute(2, 0, 1)

In [ ]:
x_original

tensor([[[0.3386, 0.4006, 0.1017],
         [0.3677, 0.6535, 0.0462]],

        [[0.4416, 0.6812, 0.7414],
         [0.8894, 0.1426, 0.2504]]])

In [ ]:
x_permuted

tensor([[[0.3386, 0.3677],
         [0.4416, 0.8894]],

        [[0.4006, 0.6535],
         [0.6812, 0.1426]],

        [[0.1017, 0.0462],
         [0.7414, 0.2504]]])

## Indexing tensors
Indexing in pytorch is similar to indexing with numpy

In [ ]:
# create a tensor:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Indexing according to the dim indices:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Indexing according to rows:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Indexing according to cols:
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [ ]:
# You can use the ':' to select all the target dimension:
# Get all the values of 0th and 1st dimensions but only index 1 of 2nd dimension:
x[:, :, 1]


tensor([[2, 5, 8]])

## PyTorch tensors and numpy

In [ ]:
# create a numpy array:
array = np.arange(1.0, 8.0)

In [ ]:
# convert numpy array to tensor:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
# Convert a tensor to numpy:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()


## Reproducibility

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
Essentially what the random seed does is flavour the randomness.

In [ ]:
# For custom operators, you might need to set python seed as well:
import random
random.seed(42)

In [ ]:
# If you or any of the libraries you are using rely on NumPy, you can seed the global NumPy RNG with:
np.random.seed(42)

In [ ]:
# Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
random_tensor_A, random_tensor_B

(tensor([[0.7118, 0.8356, 0.6420, 0.7466],
         [0.9982, 0.6997, 0.4425, 0.0855],
         [0.2081, 0.6497, 0.6547, 0.5833]]),
 tensor([[0.2449, 0.8050, 0.5863, 0.1717],
         [0.6030, 0.0023, 0.1714, 0.6504],
         [0.5491, 0.4792, 0.8478, 0.3876]]))

In [ ]:
# Let's make some random but reproducible tensors:
# Set the random seed
# We should call torch.manual_seed for every call
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)
random_tensor_A

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [ ]:
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)
random_tensor_B

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

## Runing tensors and PyTorch on the GPUs

In [ ]:
# check for GPU access with pytorch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of GPUs:
torch.cuda.device_count()

1

In [ ]:
# create a tensor by default on cpu:
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

In [ ]:
# Move tensor to GPU (if available):
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# if a tensor on gpu, we can transform it to numpy array:
tensor_back_to_cpu = tensor_to_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])